name: ElucidateDiffusion
optimizer:
  params:
    name: Adam
    lr: 5e-4
    T_max: 500000
    eta_min: 5e-6
model:
  ElucidateDiffusionParams:
    num_sample_steps: 64
    self_conditioning: false
  EMAParams:
    update_every: 10
    beta: 0.995 #ema_decay

loss_mask: false
latitude_weight: true
variable_weight: false

